### ISSUE TITLE
Bug when detecting Factorio init

### ISSUE THREAD

**Issue by LevFendi** [Factorio-Access/Factorio-Access-Launcher#2]
As found by @ohylli: 

When the launcher opens the game to create the config file, it fails to close the game. The game at this point hangs indefinitely on the in-game login screen.

At the root of this error, in fa_paths.py on line 198 it is expecting from the game's stdout "Factorio initialized", and then it kills the process, but when we look at the game's log it has "Factorio initialised".

The spelling difference may account for the hang.

**Comment by LevFendi** [comment]
By the way, perhaps the log output is sensitive to the OS locale, and so maybe detecting both spellings would be required? But in this case I would also be worried about other languages.

**Comment by EphDoering** [comment]
Pretty sure it's always the same. Like the API uses localised instead of localized.
