### ISSUE TITLE
Moving the tutorial-to-md.py script to the main repository

### ISSUE THREAD

**Issue by LevFendi** [Factorio-Access/Factorio-Access-Launcher#3]
I know that I opted for moving this script to the launcher repository to keep the python and lua files separated, but perhaps it makes more sense to have it in the main repo after all, since releases of the main repo would contain it for mod maintainers to use and the releases of the launcher repo are more about giving a main python script or an executable to run.

Furthermore, I forgot that this script was already here and added it to the main repository. We can remove it from either of the repos depending on where it makes the most sense to keep it.

Thoughts?

**Comment by EphDoering** [comment]
I agree that the files used to maintain the Lua mod should be kept with the Lua mod.

**Comment by LevFendi** [comment]
Please feel free to remove the script from this repository when convenient.
